### ISSUE TITLE
데모데이 To-do list

### ISSUE THREAD

**Issue by yezgoget** [mnxmnz/colfume-frontend#160]
## 💡 이슈 제목
웹퓸이들의 일정

## ✨ 이슈 설명
- [ ] 컬퓸 발표 듣기
- [ ] 포토이즘 찍기 전에 옷쇼핑
- [ ] 포토이즘 찍기
- [x] 회 먹기
- [ ] 주류백화점에서 와인 각 1병씩 사오기
- [ ] 1병씩 마시기
- [ ] 마시고 죽기
- [x] 기깔나게 재밌는 얘기 하기
- [x] 스플렌더 하기
- [x] 다빈치코드 하기
- [x] 11시에 체크아웃하기

## 🎯 이슈 생성 후 확인 내용
- [x] 이슈 제목 확인 
- [x] Assignees 설정 
- [x] Labels 설정 
- [x] Projects 설정

**Comment by soryeongk** [comment]
우와 너무 기대되어요!

**Comment by mnxmnz** [comment]
못한 게 너무 많아서.. 슬퍼요.. ㅠ 😢 포토이즘은 꼭 찍었어야 했는데 ㅠ 합숙 그리워요!
